version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: 3307
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        depends_on:
            - mysql
    task:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["su", "webuser", "-c", "php /var/www/html/artisan schedule:work"]
        environment:
            PHP_POOL_NAME: "my-app_task"
        depends_on:
                - app

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:latest
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - mysql_data:/var/lib/mysql
#            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    mysql_data:
